"""
EAS Station - Emergency Alert System
Copyright (c) 2025-2026 EAS Station, LLC (KR8MER)

This file is part of EAS Station.

EAS Station is dual-licensed software:
- GNU Affero General Public License v3 (AGPL-3.0) for open-source use
- Commercial License for proprietary use

You should have received a copy of both licenses with this software.
For more information, see LICENSE and LICENSE-COMMERCIAL files.

IMPORTANT: This software cannot be rebranded or have attribution removed.
See NOTICE file for complete terms.

Repository: https://github.com/KR8MER/eas-station
"""

from __future__ import annotations

"""Installing an obtained certificate into the nginx configuration."""

import subprocess
from pathlib import Path
from typing import Any, Dict

from .log import logger
from .nginx import _check_nginx_status
from .paths import CERTBOT_CONFIG_DIR


def _install_certificate_internal(domain: str) -> Dict[str, Any]:
    """Internal helper to install a certificate after it's been obtained.

    Simplified approach:
    1. Find the most recent certificate directory for the domain
    2. Verify certificate files exist
    3. Write an nginx SSL snippet pointing directly to the cert files
    4. Reload nginx

    Args:
        domain: Domain name for the certificate

    Returns:
        Dict with 'success' boolean and either 'message' or 'error' string
    """
    try:
        # Find certificate directory - certbot may create domain-0001, domain-0002, etc.
        # when obtaining multiple certs for the same domain (e.g., switching staging to production)
        live_dir = CERTBOT_CONFIG_DIR / 'live'
        
        if not live_dir.exists():
            return {
                "success": False,
                "error": f"Certificate directory not found: {live_dir}"
            }
        
        # Find all directories matching the domain (including numbered variants)
        matching_dirs = []
        try:
            for entry in live_dir.iterdir():
                if entry.is_dir() and entry.name != 'README':
                    # Match exact domain or domain-#### pattern (certbot numbered variants)
                    # Example: example.com or example.com-0001
                    # Do NOT match: example.com.test or example.com-backup
                    if entry.name == domain:
                        matching_dirs.append(entry)
                    elif entry.name.startswith(f"{domain}-"):
                        # Verify the suffix is a number (certbot style)
                        suffix = entry.name[len(domain)+1:]  # Everything after "domain-"
                        if suffix.isdigit():
                            matching_dirs.append(entry)
        except Exception as e:
            return {
                "success": False,
                "error": f"Error reading certificate directory: {str(e)}"
            }
        
        if not matching_dirs:
            return {
                "success": False,
                "error": f"Certificate not found for domain {domain}. Run 'Obtain Certificate' first."
            }
        
        # Use the most recently modified directory (latest certificate)
        if len(matching_dirs) == 1:
            # Optimization: Skip stat() calls if only one directory
            cert_dir = matching_dirs[0]
        else:
            # Cache stat results for performance
            dirs_with_mtime = [(d, d.stat().st_mtime) for d in matching_dirs]
            cert_dir = max(dirs_with_mtime, key=lambda x: x[1])[0]
        logger.info(f"Using certificate directory: {cert_dir}")
        
        fullchain_path = cert_dir / 'fullchain.pem'
        privkey_path = cert_dir / 'privkey.pem'

        # Verify certificate files exist
        if not fullchain_path.exists():
            return {
                "success": False,
                "error": f"Certificate file missing: fullchain.pem"
            }
        if not privkey_path.exists():
            return {
                "success": False,
                "error": f"Certificate file missing: privkey.pem"
            }

        # Write nginx SSL snippet that points directly to our cert files
        # This avoids all the symlink and sed complexity
        ssl_snippet_path = Path('/etc/nginx/snippets/ssl-letsencrypt.conf')
        ssl_snippet_content = f"""# Let's Encrypt SSL certificate for {domain}
# Auto-generated by EAS Station certbot manager
ssl_certificate {fullchain_path};
ssl_certificate_key {privkey_path};
"""

        # Ensure the snippets directory exists. On distros without snippets/
        # (or freshly minimal nginx installs) the subsequent `sudo tee` would
        # fail with "No such file or directory", which surfaces in the UI as
        # an inability to override the previous certificate. The sudoers
        # entry for `mkdir -p /etc/nginx/snippets` is provided for exactly
        # this reason.
        mkdir_result = subprocess.run(
            ['sudo', 'mkdir', '-p', str(ssl_snippet_path.parent)],
            capture_output=True,
            text=True,
            timeout=5
        )
        if mkdir_result.returncode != 0:
            return {
                "success": False,
                "error": f"Failed to create nginx snippets directory: {mkdir_result.stderr.strip()}"
            }

        # Write the snippet file
        write_result = subprocess.run(
            ['sudo', 'tee', str(ssl_snippet_path)],
            input=ssl_snippet_content,
            capture_output=True,
            text=True,
            timeout=5
        )

        if write_result.returncode != 0:
            return {
                "success": False,
                "error": f"Failed to write SSL snippet: {write_result.stderr.strip()}"
            }

        logger.info(f"Created SSL snippet at {ssl_snippet_path}")

        # Update the main nginx config to include our snippet instead of self-signed certs
        nginx_config_path = Path('/etc/nginx/sites-available/eas-station')

        # First, check if we need to update the config (only if it's using self-signed)
        # Use a simple sed to comment out self-signed and add our snippet include

        # Comment out any existing ssl_certificate lines and add our include
        # This is idempotent - running it multiple times is safe
        sed_commands = [
            # Comment out self-signed cert lines if present
            's|^\\(\\s*\\)ssl_certificate /etc/ssl/|\\1# ssl_certificate /etc/ssl/|g',
            's|^\\(\\s*\\)ssl_certificate_key /etc/ssl/|\\1# ssl_certificate_key /etc/ssl/|g',
            # Comment out any existing direct letsencrypt certificate path lines
            # Use \\.pem to match only direct certificate file paths, not include statements
            's|^\\(\\s*\\)ssl_certificate.*/letsencrypt/.*\\.pem|\\1# ssl_certificate_DISABLED /letsencrypt/|g',
            's|^\\(\\s*\\)ssl_certificate_key.*/letsencrypt/.*\\.pem|\\1# ssl_certificate_key_DISABLED /letsencrypt/|g',
        ]

        for sed_cmd in sed_commands:
            subprocess.run(
                ['sudo', 'sed', '-i', sed_cmd, str(nginx_config_path)],
                capture_output=True,
                text=True,
                timeout=5
            )

        # Check if the include line already exists. Use sudo for the read so
        # we don't silently treat a "permission denied" as "include missing"
        # and end up appending a duplicate include line on every install.
        grep_result = subprocess.run(
            ['sudo', 'grep', '-q', 'ssl-letsencrypt.conf', str(nginx_config_path)],
            capture_output=True,
            timeout=5
        )

        if grep_result.returncode != 0:
            # Include line doesn't exist, add it after the ssl_protocols line
            subprocess.run(
                ['sudo', 'sed', '-i',
                 '/ssl_protocols/a\\    include snippets/ssl-letsencrypt.conf;',
                 str(nginx_config_path)],
                capture_output=True,
                text=True,
                timeout=5
            )
            logger.info("Added SSL snippet include to nginx config")

        logger.info(f"Updated nginx configuration to use Let's Encrypt certificate for {domain}")

        # Validate nginx config before touching the running service. `systemctl
        # reload nginx` reports a generic non-zero exit on config errors, but
        # `nginx -t` returns the actual problem (e.g. missing snippet file,
        # syntax error from a stale ssl_certificate line) — surface that to
        # the user so the "issue overriding the old one" is debuggable.
        test_result = subprocess.run(
            ['sudo', 'nginx', '-t'],
            capture_output=True,
            text=True,
            timeout=10
        )
        if test_result.returncode != 0:
            nginx_diag = (test_result.stderr or test_result.stdout or '').strip()
            logger.error(f"nginx -t rejected the updated config: {nginx_diag}")
            return {
                "success": False,
                "error": f"nginx configuration test failed: {nginx_diag}"
            }

        # Check if nginx is running before attempting reload
        nginx_running = _check_nginx_status()

        if nginx_running:
            # Nginx is running - use reload (graceful, no downtime)
            logger.info("Reloading nginx to apply certificate changes")
            reload_result = subprocess.run(
                ['sudo', 'systemctl', 'reload', 'nginx'],
                capture_output=True,
                text=True,
                timeout=10
            )

            if reload_result.returncode != 0:
                # Reload failed, try restart as fallback
                logger.warning(f"Nginx reload failed: {reload_result.stderr}, attempting restart")
                restart_result = subprocess.run(
                    ['sudo', 'systemctl', 'restart', 'nginx'],
                    capture_output=True,
                    text=True,
                    timeout=10
                )

                if restart_result.returncode != 0:
                    return {
                        "success": False,
                        "error": f"Failed to reload/restart nginx: {restart_result.stderr.strip()}"
                    }
                logger.info("Nginx restarted successfully with new certificate")
            else:
                logger.info("Nginx reloaded successfully with new certificate")
        else:
            # Nginx is not running - start it
            logger.warning("Nginx not running, starting it with new certificate configuration")
            start_result = subprocess.run(
                ['sudo', 'systemctl', 'start', 'nginx'],
                capture_output=True,
                text=True,
                timeout=10
            )
            
            if start_result.returncode != 0:
                return {
                    "success": False,
                    "error": f"Failed to start nginx: {start_result.stderr}"
                }
            logger.info("Nginx started successfully with new certificate")
        
        return {
            "success": True,
            "message": f"Certificate installed successfully for {domain}",
            "details": {
                "domain": domain,
                "cert_path": str(cert_dir),
                "ssl_snippet": str(ssl_snippet_path),
                "nginx_config": str(nginx_config_path)
            }
        }

    except subprocess.TimeoutExpired as e:
        logger.error(f"Timeout during certificate installation: {e.cmd}")
        return {
            "success": False,
            "error": f"Timeout during certificate installation (command: {' '.join(str(c) for c in e.cmd) if hasattr(e, 'cmd') else 'unknown'})"
        }
    except Exception as e:
        logger.error(f"Failed to install certificate: {e}")
        return {
            "success": False,
            "error": f"Failed to install certificate: {str(e)}"
        }
