#!/usr/bin/env python3
"""
EAS Station - Emergency Alert System
Copyright (c) 2025-2026 EAS Station, LLC (KR8MER)

This file is part of EAS Station.

EAS Station is dual-licensed software:
- GNU Affero General Public License v3 (AGPL-3.0) for open-source use
- Commercial License for proprietary use

You should have received a copy of both licenses with this software.
For more information, see LICENSE and LICENSE-COMMERCIAL files.

IMPORTANT: This software cannot be rebranded or have attribution removed.
See NOTICE file for complete terms.

Repository: https://github.com/KR8MER/eas-station
"""

"""Tests for the live repository statistics page.

The statistics used to be a committed ``static/repo_stats.html`` blob
regenerated by a script, so the tests could only assert on stale strings. The
page is now computed on demand from the working tree, so these tests exercise
the analyser itself: bucket classification, line counting, caching, and that
the page and its JSON sibling render.
"""

from pathlib import Path

import pytest

from app_utils import repo_stats


REPO_ROOT = Path(__file__).resolve().parent.parent


@pytest.fixture(autouse=True)
def _clear_cache():
    """Each test starts from a cold cache."""
    repo_stats.invalidate_cache()
    yield
    repo_stats.invalidate_cache()


@pytest.fixture(scope='module')
def sample_tree(tmp_path_factory):
    """A tiny repository-shaped tree with one file per bucket."""
    root = tmp_path_factory.mktemp('sample_repo')

    (root / 'webapp').mkdir()
    (root / 'webapp' / 'views.py').write_text(
        '"""Module docstring."""\n'
        '\n'
        '# a comment\n'
        'import os\n'
        '\n'
        'def handler():\n'
        '    return os.getcwd()\n',
        encoding='utf-8',
    )

    (root / 'docs').mkdir()
    (root / 'docs' / 'GUIDE.md').write_text('# Guide\n\nSome prose.\n', encoding='utf-8')

    vendor = root / 'static' / 'vendor' / 'chartjs'
    vendor.mkdir(parents=True)
    (vendor / 'chart.min.js').write_text('var Chart=function(){};\n', encoding='utf-8')

    return root


# ---------------------------------------------------------------------------
# Classification
# ---------------------------------------------------------------------------

@pytest.mark.parametrize('path,expected', [
    ('app.py', 'project'),
    ('webapp/routes_public.py', 'project'),
    ('templates/base.html', 'project'),
    ('static/css/styles.css', 'project'),
    ('systemd/eas-station-web.service', 'project'),
    ('README.md', 'docs'),
    ('docs/reference/CHANGELOG.md', 'docs'),
    ('requirements.txt', 'docs'),
    ('static/vendor/bootstrap/bootstrap.min.css', 'vendored'),
    ('static/vendor/chartjs/chart.min.js', 'vendored'),
    ('node_modules/left-pad/index.js', 'vendored'),
    ('static/js/core/theme.min.js', 'vendored'),
])
def test_classify_buckets(path, expected):
    assert repo_stats.classify(path) == expected


def test_vendored_assets_are_not_counted_as_project_code(sample_tree):
    """The bug the old page shipped: vendor code inflating the headline totals."""
    stats = repo_stats.compute_stats(root=sample_tree)

    project = stats['buckets']['project']
    vendored = stats['buckets']['vendored']

    assert project['files'] == 1, 'only webapp/views.py is first-party here'
    assert vendored['files'] == 1, 'chart.min.js must land in the vendored bucket'
    assert vendored['code'] > 0
    # The vendored line must not appear anywhere in the project totals.
    assert project['code'] < vendored['code'] + project['total']
    assert stats['buckets']['docs']['files'] == 1


def test_buckets_partition_all_files(sample_tree):
    """Every counted file belongs to exactly one bucket."""
    stats = repo_stats.compute_stats(root=sample_tree)
    bucketed = sum(stats['buckets'][name]['files'] for name in repo_stats.BUCKETS)
    assert bucketed == stats['total_files']


# ---------------------------------------------------------------------------
# Component inventory
# ---------------------------------------------------------------------------

def test_services_blueprints_and_models_are_counted(tmp_path):
    """services/*/api.py defines real Blueprints; the scan must not skip them.

    The bug the page shipped with: ``count_components`` only scanned
    ``app_core/`` and ``webapp/``, so the zigbee/network/gps/displays
    Blueprints -- the same modules whose routes the source-scan fallback
    already counts -- never showed up in the Blueprints tile.
    """
    (tmp_path / 'services' / 'zigbee').mkdir(parents=True)
    (tmp_path / 'services' / 'zigbee' / 'api.py').write_text(
        'from flask import Blueprint\n'
        'bp = Blueprint("zigbee_api", __name__)\n',
        encoding='utf-8',
    )
    (tmp_path / 'app_core').mkdir()
    (tmp_path / 'app_core' / 'models.py').write_text(
        'class Widget(db.Model):\n    pass\n',
        encoding='utf-8',
    )

    files, _ = repo_stats.discover_files(tmp_path)
    components = repo_stats.count_components(tmp_path, files)

    assert components['blueprints'] == 1
    assert components['models'] == 1


def test_root_level_operator_scripts_are_counted(tmp_path):
    """install.sh/app.py etc. live at the repo root, not under scripts/."""
    (tmp_path / 'install.sh').write_text('#!/bin/bash\necho hi\n', encoding='utf-8')
    (tmp_path / 'app.py').write_text('print("hi")\n', encoding='utf-8')
    (tmp_path / 'scripts').mkdir()
    (tmp_path / 'scripts' / 'backfill.py').write_text('print("hi")\n', encoding='utf-8')

    files, _ = repo_stats.discover_files(tmp_path)
    components = repo_stats.count_components(tmp_path, files)

    assert components['scripts'] == 3


# ---------------------------------------------------------------------------
# Line counting
# ---------------------------------------------------------------------------

def test_python_line_counting(tmp_path):
    source = tmp_path / 'module.py'
    source.write_text(
        '"""One-line docstring."""\n'   # comment (must not open a block)
        '# comment\n'                   # comment
        'x = 1\n'                       # code
        '\n'                            # blank
        '"""\n'                         # comment (opens block)
        'block\n'                       # comment
        '"""\n'                         # comment (closes block)
        'y = 2\n',                      # code
        encoding='utf-8',
    )

    total, code, comments = repo_stats.count_lines(source, '.py')
    assert total == 8
    assert code == 2, 'a one-line docstring must not swallow the rest of the file'
    assert comments == 5
    assert total - code - comments == 1, 'one blank line'


def test_unreadable_file_is_counted_as_zero(tmp_path):
    missing = tmp_path / 'not-there.py'
    assert repo_stats.count_lines(missing, '.py') == (0, 0, 0)


# ---------------------------------------------------------------------------
# The real repository
# ---------------------------------------------------------------------------

def test_real_repository_snapshot_is_sane():
    stats = repo_stats.compute_stats()

    assert stats['file_source'] in {'git', 'walk'}
    assert stats['total_files'] > 100
    assert stats['directories'] > 10

    project = stats['buckets']['project']
    assert project['files'] > 100
    assert project['code'] > 10000
    assert project['blank'] >= 0
    assert project['languages'], 'expected a language breakdown'
    assert project['languages'][0]['name'] == 'Python'

    components = stats['components']
    assert components['templates'] > 50
    assert components['tests'] > 50
    assert components['migrations'] > 50
    assert components['blueprints'] > 5
    assert components['models'] > 5


def test_route_count_includes_named_blueprints():
    """The old regex only matched @app.route/@bp.route and missed ~half the app."""
    stats = repo_stats.compute_stats()
    assert stats['routes']['total'] > 400, (
        'route count looks like the old @app|@bp-only regex'
    )
    assert stats['routes']['by_module'], 'expected a per-module breakdown'


def test_git_history_reports_commits_and_contributors():
    stats = repo_stats.compute_stats()
    if stats['file_source'] != 'git':
        pytest.skip('not a git checkout in this environment')

    history = stats['git_history']
    assert history is not None
    assert history['commits'] > 100
    assert history['contributors'] >= 1
    assert history['last_commit_at'], 'expected an ISO-formatted commit date'


def test_git_history_is_none_outside_a_git_checkout(tmp_path):
    """A non-git tree must hide the tile, not render a misleading zero."""
    (tmp_path / 'README.md').write_text('# hi\n', encoding='utf-8')
    stats = repo_stats.compute_stats(root=tmp_path)
    assert stats['file_source'] == 'walk'
    assert stats['git_history'] is None


def test_cache_is_reused_until_invalidated():
    first = repo_stats.get_stats()
    second = repo_stats.get_stats()
    assert first is second, 'a warm cache must not recompute'

    repo_stats.invalidate_cache()
    third = repo_stats.get_stats()
    assert third is not first


def test_generated_stats_are_json_serialisable():
    import json

    stats = repo_stats.compute_stats()
    round_tripped = json.loads(json.dumps(stats))
    assert round_tripped['total_files'] == stats['total_files']


# ---------------------------------------------------------------------------
# Wiring
# ---------------------------------------------------------------------------

def test_old_generated_artifacts_are_gone():
    """The stale generate-and-commit pipeline must stay deleted."""
    assert not (REPO_ROOT / 'static' / 'repo_stats.html').exists()
    assert not (REPO_ROOT / 'scripts' / 'generate_repo_stats.py').exists()
    assert not (REPO_ROOT / '.github' / 'workflows' / 'update-repo-stats.yml').exists()


def test_page_template_extends_base_and_uses_standard_header():
    page = (REPO_ROOT / 'templates' / 'repo_stats.html').read_text(encoding='utf-8')
    content = (REPO_ROOT / 'templates' / 'repo_stats' / '_content.html').read_text(encoding='utf-8')

    assert '{% extends "base.html" %}' in page
    assert "{% include 'components/page_header.html' %}" in content
    assert '{% block scripts %}' in page, 'page JS must use the real block name'
    assert '{% block extra_js %}' not in page

    # Chart.js must come from the vendored copy, never a CDN.
    assert "vendor/chartjs/chart.min.js" in page
    assert 'cdn.jsdelivr.net' not in page and 'cdnjs.cloudflare.com' not in page


def test_page_uses_only_defined_css_variables():
    """The old page painted with --gradient-start/--gradient-end, which never existed."""
    styles = (REPO_ROOT / 'static' / 'css' / 'styles.css').read_text(encoding='utf-8')
    sources = [
        (REPO_ROOT / 'templates' / 'repo_stats.html').read_text(encoding='utf-8'),
        (REPO_ROOT / 'templates' / 'repo_stats' / '_content.html').read_text(encoding='utf-8'),
        (REPO_ROOT / 'templates' / 'repo_stats' / '_scripts.html').read_text(encoding='utf-8'),
    ]

    import re
    used = set()
    for source in sources:
        used.update(re.findall(r'var\(\s*(--[a-z0-9-]+)', source))
        used.update(re.findall(r"cssVar\(\s*'(--[a-z0-9-]+)'", source))

    assert used, 'expected the page to use theme variables'
    undefined = sorted(name for name in used if f'{name}:' not in styles)
    assert not undefined, f'page references undefined CSS variables: {undefined}'


# ---------------------------------------------------------------------------
# Language logos and the shared dashboard idiom
# ---------------------------------------------------------------------------

LOGO_DIR = REPO_ROOT / 'static' / 'img' / 'logos'


def test_every_mapped_language_logo_file_exists():
    """A missing SVG renders as a broken image, so pin the files down."""
    missing = [
        f'{language} -> {filename}'
        for language, filename in repo_stats.LANGUAGE_LOGOS.items()
        if not (LOGO_DIR / filename).is_file()
    ]
    assert not missing, f'mapped logos with no file under static/img/logos/: {missing}'


def test_every_tracked_language_has_a_logo_or_glyph():
    """No language may render with a bare, unlabelled cell."""
    languages = set(repo_stats.LANGUAGES.values())
    unmarked = sorted(
        name for name in languages
        if name not in repo_stats.LANGUAGE_LOGOS
        and name not in repo_stats.LANGUAGE_GLYPHS
    )
    assert not unmarked, f'languages with neither a logo nor a glyph: {unmarked}'


def test_language_entries_carry_logo_and_glyph():
    stats = repo_stats.compute_stats()
    languages = stats['buckets']['project']['languages']
    assert languages
    for entry in languages:
        assert 'logo' in entry, f'{entry["name"]} is missing a logo key'
        assert entry.get('glyph'), f'{entry["name"]} is missing a glyph fallback'


def test_logo_svgs_are_wellformed():
    import xml.etree.ElementTree as ET

    for filename in sorted(set(repo_stats.LANGUAGE_LOGOS.values())):
        path = LOGO_DIR / filename
        root = ET.parse(path).getroot()
        assert root.tag.endswith('svg'), f'{filename} is not an <svg> document'
        assert root.get('viewBox'), f'{filename} has no viewBox, so it will not scale'


def test_page_uses_the_shared_dashboard_idiom():
    """The page should read like System Health / GNSS, not invent its own tiles."""
    content = (REPO_ROOT / 'templates' / 'repo_stats' / '_content.html').read_text(encoding='utf-8')

    assert 'status-strip' in content, 'headline figures should use the shared strip'
    assert 'status-tile' in content, 'readouts should use the shared tile'
    assert 'status-pill' in content, 'header should carry live status pills'
    assert 'ti-logo' in content, 'language rows should render brand marks'

    # Those utilities must be the shared ones, not redefined on this page.
    page = (REPO_ROOT / 'templates' / 'repo_stats.html').read_text(encoding='utf-8')
    for utility in ('.status-tile', '.status-strip', '.status-pill', '.ti-logo'):
        assert utility not in page, f'{utility} must come from styles.css, not this page'


def test_ti_logo_is_a_shared_utility():
    """It was scoped to the Traffic dashboard; two pages now render logo marks."""
    styles = (REPO_ROOT / 'static' / 'css' / 'styles.css').read_text(encoding='utf-8')
    traffic = (REPO_ROOT / 'templates' / 'security' / '_traffic_styles.html').read_text(encoding='utf-8')

    assert '.ti-logo {' in styles, '.ti-logo should be defined once, in styles.css'
    assert '.traffic-dash-root .ti-logo' not in traffic, (
        'the page-scoped copy should be gone now that the rule is shared'
    )


def test_theme_repaint_does_not_mutate_chart_options():
    """Two ways of repainting charts are broken; the script must use neither.

    Writing a value read out of ``chart.options`` back into itself builds a
    self-referential proxy that blows the stack. Setting only ``Chart.defaults``
    leaves per-scale tick colours resolved at construction, so charts keep the
    previous theme's colours — invisible until you switch themes.
    """
    scripts = (REPO_ROOT / 'templates' / 'repo_stats' / '_scripts.html').read_text(encoding='utf-8')

    assert 'chart.options.plugins' not in scripts, (
        'do not assign into the resolved-options proxy'
    )
    assert 'Chart.getChart(' in scripts and '.destroy()' in scripts, (
        'theme changes must rebuild the charts so scale options are re-resolved'
    )


def test_repo_stats_is_registered_in_navigation():
    from webapp.navigation import registry

    hrefs = []
    for section in registry.NAVIGATION:
        for group in section.groups:
            for item in group.items:
                hrefs.append(item.href)

    assert '/repo-stats' in hrefs, 'the page must be reachable from the nav registry'
