"""
EAS Station - Emergency Alert System
Copyright (c) 2025-2026 EAS Station, LLC (KR8MER)

This file is part of EAS Station.

EAS Station is dual-licensed software:
- GNU Affero General Public License v3 (AGPL-3.0) for open-source use
- Commercial License for proprietary use

You should have received a copy of both licenses with this software.
For more information, see LICENSE and LICENSE-COMMERCIAL files.

IMPORTANT: This software cannot be rebranded or have attribution removed.
See NOTICE file for complete terms.

Repository: https://github.com/KR8MER/eas-station
"""

from __future__ import annotations

"""The /alerts browse surface and its PDF export.

Both routes are glue. The page's stages live in ``webapp/public/alerts_page/``
and each degrades on its own, so the handlers here catch only a failure of the
assembly itself.
"""

from datetime import datetime

from app_core.extensions import db
from app_utils.pdf_generator import generate_pdf_document
from flask import Response, render_template, request

from .alerts_page import (
    MAX_EXPORT_ALERTS,
    build_alerts_page,
    build_export_query,
    build_export_sections,
    build_filter_summary,
)

PDF_FOOTER = "Generated by EAS Station™ — Emergency Alert System Platform"


def register(app, route_logger) -> None:
    """Attach the alerts routes to the Flask app."""
    @app.route("/alerts")
    def alerts():
        try:
            # Rollback any failed transaction before starting new queries.
            # This prevents "current transaction is aborted" errors that occur
            # when a previous request left the connection in a bad state.
            # PostgreSQL requires a rollback before new commands can be issued
            # when a transaction has failed. Defensive, for robustness.
            try:
                db.session.rollback()
            except Exception:
                pass

            return render_template(
                "alerts.html", **build_alerts_page(request, route_logger)
            )
        except Exception as exc:  # pragma: no cover - fallback content
            db.session.rollback()
            route_logger.error("Error loading alerts: %s", exc)
            return (
                "<h1>Error loading alerts</h1>"
                f"<p>{exc}</p><p><a href='/'>← Back to Main</a></p>"
            )

    @app.route("/alerts/export.pdf")
    def alerts_export_pdf():
        """Export the alerts list as a PDF, rendered server-side from the database.

        Honours the same search / status / severity / event / source /
        show_expired filters the page offers — but **not** its date range, VTEC
        or superseded rules. See ``alerts_page/pdf_export.py`` for why.

        Returns a PDF with an inline Content-Disposition and a dated filename,
        capped at ``MAX_EXPORT_ALERTS`` rows with descriptions truncated. Text
        only: no audio or other multimedia.

        See also: the ``/alerts`` route, ``/alerts/<id>/export.pdf`` for a
        single alert, and ``docs/alerts-pdf-export.md``.
        """
        try:
            alerts_list = build_export_query(request.args).limit(MAX_EXPORT_ALERTS).all()

            pdf_bytes = generate_pdf_document(
                title="Alerts Export",
                sections=build_export_sections(alerts_list),
                subtitle=build_filter_summary(request.args),
                footer_text=PDF_FOOTER,
            )

            response = Response(pdf_bytes, mimetype="application/pdf")
            response.headers["Content-Disposition"] = (
                f"inline; filename=alerts_export_{datetime.now().strftime('%Y%m%d')}.pdf"
            )
            return response

        except Exception as exc:
            db.session.rollback()
            route_logger.error("Error generating alerts PDF: %s", exc)
            return (
                "<h1>Error generating PDF</h1>"
                f"<p>{exc}</p><p><a href='/alerts'>← Back to Alerts</a></p>"
            )


__all__ = ["register"]
