name: eas-station
on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: DOCKER_PAT   # <-- this makes env secrets/vars available
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}    # env variable
          password: ${{ secrets.DOCKER_PAT }}  # env secret

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: kr8mer/eas-station:latest
          platforms: linux/amd64,linux/arm64
